modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Raysor"
description='''
Echo Of The Void transforms familiar Minecraft threats into uncanny mirrors.
As global phases advance, natural monster spawns are increasingly replaced by
silent or behavior-shifted variants until the world is fully corrupted.
'''

[[mixins]]
config="${mod_id}.client.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

