modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Raysor"
description='''
Echo Of The Void turns familiar Minecraft rules into a gradual horror campaign.
Shared anomalies, altered creatures, hostile Specials and rare major encounters
build an unpredictable but fair progression through a world that no longer feels stable.
'''

[[mixins]]
config="${mod_id}.darkness.mixins.json"

[[mixins]]
config="${mod_id}.weather.mixins.json"

[[mixins]]
config="${mod_id}.variant.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

